# Cadastro do usuario
GET  http://localhost:3001/register

###

POST http://localhost:3001/auth/register
Content-Type: application/json

{
    "name": "Levi mategheues",
    "email": "desenvolvedor.1re12322gmail.com",
    "password": "lg233242fe34",
    "telefone": "934843220fe02387",
    "ddd": "14"
}

###