# Cadastro do usuario

#Teste localhost
GET  https://localhost:80/auth/register:80/register

###

POST  https://localhost:80/auth/register
Content-Type: application/json

{
    "name": "Levi fsefsdfs",
    "email": "desenvosdflvedor.dfd.com",
    "password": "lg23sdf3242veddffe34",
    "telefone": "23412234",
    "ddd": "74"
}

###
#teste com URL
GET  http://api-rest-nodejs-production-0433.up.railway.app:80/register

###

POST http://api-rest-nodejs-production-0433.up.railway.app:80/auth/register
Content-Type: application/json

{
    "name": "Levi fsefsdfs",
    "email": "desenvosdflvedor.dfd.com",
    "password": "lg23sdf3242veddffe34",
    "telefone": "23412234",
    "ddd": "74"
}

###