# Cadastro do usuario
GET  http://localhost:3001/register

###

POST http://localhost:3001/auth/register
Content-Type: application/json

{
    "name": "Levi fsfs",
    "email": "desenvolvedor.dfd.com",
    "password": "lg233242veddffe34",
    "telefone": "234234",
    "ddd": "44"
}

###